### ISSUE TITLE
Re-write Thonny's webpage

### ISSUE THREAD

**Issue by hatlesshacker** [thonny/thonny-webpage#2]
Hello ^_^

I've worked in the project before, [thonny/thonny/pull/1053] And I just noticed the web page's repository; I believe I can re-write the web page to make it more user friendly. Should I give it a try?

**Comment by aivarannamaa** [comment]
Sure, but please show me a sketch before you start spending lot of time on it! I'd be sad if you wasted too much of your time just to find out that our perceptions of user-friendliness don't align.

**Comment by hatlesshacker** [comment]
Sure! I'll drop you an email when I have a sketch :-)
