### ISSUE TITLE
Current version is outdated on site

### ISSUE THREAD

**Issue by andypiper** [thonny/thonny-webpage#5]
The Thonny webpage is showing 3.3.13 as the version to download (top right). I was going to send a PR to update this to show 3.3.14 - but I noticed that the [release for 3.3.14](https://github.com/thonny/thonny/releases/tag/v3.3.14) does not currently have binary builds listed.

**Comment by aivarannamaa** [comment]
The reason for creating 3.3.14 was certain metadata changes which are important only for Flatpak build of Thonny. Therefore I've decided to skip the binaries for this release and work towards 4.0 instead.
