### ISSUE TITLE
consider using GitHub corner over older GitHub ribbon

### ISSUE THREAD

**Issue by hirehamir** [thonny/thonny-webpage#9]
I think using https://github.com/tholman/github-corners might provide a nicer aesthetic to https://thonny.org/.

https://thonny.org/ currently looks like this.

![image](https://github.com/thonny/thonny-webpage/assets/43425812/a88dc982-8b36-40db-a1f6-baf35907fae6)

**Comment by aivarannamaa** [comment]
Thanks! Done now.

**Comment by hirehamir** [comment]
You're welcome! I'm happy to help.
